on: 
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/actions/login@49ef4376aaf4635581bf8de870daef2a93353a91
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate namespace
      uses: okteto/actions/namespace@49ef4376aaf4635581bf8de870daef2a93353a91
      with:
        namespace: movies-preview-rberrelleza
    
    - name: Deploy Application
      uses: okteto/actions/deploy-application@49ef4376aaf4635581bf8de870daef2a93353a91
      with:
        application: movies
        name: pr-${{ github.event.number }}
        configuration: preview-config.yaml

    - name: Push API Changes
      uses: okteto/actions/push@ca4a4a5068b91bec0ef6f0d572ad67a69a818c7a
      with:
        working-directory: api

    - name: Push Frontend Changes
      uses: okteto/actions/push@ca4a4a5068b91bec0ef6f0d572ad67a69a818c7a
      with:
        working-directory: frontend
    
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Preview environment available at https://pr-${{ github.event.number }}-movies-preview-rberrelleza.cloud.okteto.net"
        
        
