on: 
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/actions/login@d3b25b13412f4e7d99ff77bf55f1f5381e641e6e
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate namespace
      uses: okteto/actions/namespace@d3b25b13412f4e7d99ff77bf55f1f5381e641e6e
      with:
        namespace: movies-preview-rberrelleza
    
    - name: Deploy Application
      uses: okteto/actions/deploy-application@d3b25b13412f4e7d99ff77bf55f1f5381e641e6e
      with:
        namespace: movies-preview-rberrelleza
        application: movies
        name: pr-${{ github.event.number }}
        configuration: preview-config.yaml
        repository: https://apps.okteto.com
    
    - name: Wait / Sleep
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'

    - name: Push API Changes
      uses: okteto/actions/push@d3b25b13412f4e7d99ff77bf55f1f5381e641e6e
      with:
        working-directory: api

    - name: Push Frontend Changes
      uses: okteto/actions/push@d3b25b13412f4e7d99ff77bf55f1f5381e641e6e
      with:
        working-directory: frontend
    
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Preview environment available at https://pr-${{ github.event.number }}-movies-preview-rberrelleza.cloud.okteto.net"
        
        
