on: 
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/actions/login@575c7be4a5b3ba8a208cfdc2e3849f1ef3cb926d
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate namespace
      uses: okteto/actions/namespace@575c7be4a5b3ba8a208cfdc2e3849f1ef3cb926d
      with:
        namespace: movies-preview-rberrelleza
    
    - name: Deploy Application
      uses: okteto/actions/deploy-application@575c7be4a5b3ba8a208cfdc2e3849f1ef3cb926d
      with:
        namespace: movies-preview-rberrelleza
        application: movies
        name: pr-${{ github.event.number }}
        configuration: preview-config.yaml
        repository: https://apps.okteto.com
    
    - name: Wait / Sleep
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'

    - name: Push API Changes
      uses: okteto/actions/push@575c7be4a5b3ba8a208cfdc2e3849f1ef3cb926d
      with:
        working-directory: api

    - name: Push Frontend Changes
      uses: okteto/actions/push@575c7be4a5b3ba8a208cfdc2e3849f1ef3cb926d
      with:
        working-directory: frontend
    
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Preview environment available at https://pr-${{ github.event.number }}-movies-preview-rberrelleza.cloud.okteto.net"
        
        
